### ISSUE TITLE
Release fails when pyproject.toml file is not there

### ISSUE THREAD

**Issue by mauritsvanrees** [collective/zestreleaser.towncrier#2]
```
$ fullrelease 
INFO: Starting prerelease.
Traceback (most recent call last):
  File "/Users/maurits/tools/bin/fullrelease", line 41, in <module>
    sys.exit(zest.releaser.fullrelease.main())
  File "/Users/maurits/tools/src/zest.releaser/zest/releaser/fullrelease.py", line 23, in main
    prereleaser.run()
  File "/Users/maurits/tools/src/zest.releaser/zest/releaser/baserelease.py", line 388, in run
    self._run_hooks('before')
  File "/Users/maurits/tools/src/zest.releaser/zest/releaser/baserelease.py", line 385, in _run_hooks
    utils.run_hooks(self.setup_cfg, which_releaser, when, self.data)
  File "/Users/maurits/tools/src/zest.releaser/zest/releaser/utils.py", line 679, in run_hooks
    run_entry_points(which_releaser, when, data)
  File "/Users/maurits/tools/src/zest.releaser/zest/releaser/utils.py", line 695, in run_entry_points
    plugin(data)
  File "/Users/maurits/shared-eggs/cp27m/zestreleaser.towncrier-1.0.0b1-py2.7.egg/zestreleaser/towncrier/__init__.py", line 78, in check_towncrier
    result = _is_towncrier_enabled()
  File "/Users/maurits/shared-eggs/cp27m/zestreleaser.towncrier-1.0.0b1-py2.7.egg/zestreleaser/towncrier/__init__.py", line 60, in _is_towncrier_enabled
    if not _load_config():
  File "/Users/maurits/shared-eggs/cp27m/zestreleaser.towncrier-1.0.0b1-py2.7.egg/zestreleaser/towncrier/__init__.py", line 38, in _load_config
    with open(TOWNCRIER_CONFIG_FILE, 'r') as conffile:
IOError: [Errno 2] No such file or directory: 'pyproject.toml'
```
I thought I had that covered, but apparently not.

**Comment by mauritsvanrees** [comment]
Fixed in 1.0.0b2.
